//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elite
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientInfo
    {
        public int ClientinfoID { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<byte> Age { get; set; }
        public string PrimaryPhone { get; set; }
        public bool PublicAssist { get; set; }
        public int ClientID { get; set; }
        public bool Conviction { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
